version: '3.8'

services:
  # Official Calibre-Web-Automated  
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: cwa-official
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    ports:
      - "8083:8083"
    volumes:
      # Use local directories for easy access
      - ./cwa-data/config:/config
      - ./cwa-data/library:/calibre-library
      - ./ingest:/cwa-book-ingest
    restart: unless-stopped
    networks:
      - cwa-network

  # Our Flask API and Modern Frontend
  cwa-downloader-api:
    build:
      context: .
      dockerfile: Dockerfile.fullstack
    container_name: cwa-api
    environment:
      - FLASK_PORT=8084
      - FLASK_HOST=0.0.0.0
      - DEBUG=true
      - APP_ENV=development
      - LOG_LEVEL=DEBUG
      - ENABLE_LOGGING=true
      - BOOK_LANGUAGE=en
      - USE_BOOK_TITLE=true
      - MAX_CONCURRENT_DOWNLOADS=3
      - TZ=America/New_York
      
      # Database paths (shared with CWA)
      - CWA_DB_PATH=/app/data/cwa.db
      
      # CWA connection (internal network)
      - CWA_BASE_URL=http://calibre-web-automated:8083
      - CWA_USERNAME=admin
      - CWA_PASSWORD=admin123
      
    ports:
      - "8084:8084"
    volumes:
      # Local directories for easy development
      - ./data:/app/data
      - ./logs:/app/logs
      - ./ingest:/app/ingest
      
      # Access to CWA's library data (read-only)
      - ./cwa-data/library:/app/cwa-library:ro
      
    restart: unless-stopped
    depends_on:
      - calibre-web-automated
    networks:
      - cwa-network

networks:
  cwa-network:
    driver: bridge